In [1]:
import torch
import clip
from PIL import Image

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
model, preprocess = clip.load("ViT-B/32", device=device)

In [19]:
import requests

image = Image.open(requests.get("https://www.adobe.com/acrobat/hub/media_173d13651460eb7e12c0ef4cf8410e0960a20f0ee.jpg", stream=True).raw)
image_inputs = torch.stack([preprocess(image).to(device) for _ in range(2)])
image_inputs

tensor([[[[-1.0769, -1.0769, -1.0915,  ..., -0.2594, -0.3762, -0.5514],
          [-1.0623, -1.0623, -1.0769,  ..., -0.6098, -0.7120, -0.7704],
          [-1.0915, -1.0915, -1.1061,  ..., -0.9456, -0.9456, -0.9602],
          ...,
          [ 0.9814,  0.9814,  0.9814,  ...,  1.0690,  1.0690,  1.0836],
          [ 0.9230,  0.9522,  0.9522,  ...,  1.0690,  1.0836,  1.0982],
          [ 0.8938,  0.9084,  0.9230,  ...,  1.0544,  1.0836,  1.0982]],

         [[-1.1968, -1.1968, -1.2118,  ..., -0.5365, -0.6115, -0.6865],
          [-1.1368, -1.1518, -1.1668,  ..., -0.7466, -0.8216, -0.8666],
          [-1.1668, -1.1668, -1.1668,  ..., -0.9567, -0.9717, -0.9717],
          ...,
          [ 0.7992,  0.8142,  0.7992,  ...,  0.9193,  0.9343,  0.9343],
          [ 0.7692,  0.7842,  0.7842,  ...,  0.9343,  0.9493,  0.9793],
          [ 0.7242,  0.7542,  0.7542,  ...,  0.9343,  0.9643,  0.9943]],

         [[-1.1674, -1.1816, -1.1958,  ..., -0.9256, -0.9541, -1.0252],
          [-1.0963, -1.0963, -

In [20]:
with torch.no_grad():
    image_feature = model.encode_image(image_inputs)
image_feature

tensor([[0.1534, 0.0992, 0.2134,  ..., 0.2330, 0.1202, 0.4976],
        [0.1534, 0.0992, 0.2134,  ..., 0.2330, 0.1202, 0.4976]],
       device='cuda:0', dtype=torch.float16)

In [22]:
with torch.no_grad():
    features = model.encode_image(image_inputs)
    features /= features.norm(dim=-1, keepdim=True)
features


tensor([[0.0129, 0.0083, 0.0179,  ..., 0.0195, 0.0101, 0.0417],
        [0.0129, 0.0083, 0.0179,  ..., 0.0195, 0.0101, 0.0417]],
       device='cuda:0', dtype=torch.float16)